global using IDPLibrary.Entities.Interfaces.Endpoints;
global using Microsoft.AspNetCore.Http;
global using IDPLibrary.Endpoints;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.AspNetCore.Builder;
global using IDPLibrary.Entities.Options;
global using Microsoft.Extensions.Options;
global using IDPLibrary.Entities.ValueObjects;
